// <auto-generated />
using CuratorBook.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace CuratorBookCore.Migrations
{
    [DbContext(typeof(CuratorBookDbContext))]
    partial class CuratorBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CuratorBookCore.Data.Tables.Controls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Controls");
                });

            modelBuilder.Entity("CuratorBookCore.Data.Tables.Forms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.Property<int>("PageId");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("CuratorBookCore.Data.Tables.FormsControls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnswerId")
                        .HasMaxLength(50);

                    b.Property<int>("ControlId");

                    b.Property<int>("FormId");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("FormId");

                    b.ToTable("FormsControls");
                });

            modelBuilder.Entity("CuratorBookCore.Data.Tables.Pages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("CuratorBookCore.Data.Tables.Forms", b =>
                {
                    b.HasOne("CuratorBookCore.Data.Tables.Pages", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CuratorBookCore.Data.Tables.FormsControls", b =>
                {
                    b.HasOne("CuratorBookCore.Data.Tables.Controls", "Type")
                        .WithMany()
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CuratorBookCore.Data.Tables.Forms", "Form")
                        .WithMany("Controls")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
